# version: "3.9"

services:
  fastapi_app:
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src  # mount mã nguồn để auto reload khi chỉnh sửa
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock  # optional nếu có lockfile
    env_file:
      - .env
    depends_on:
      - redis_server
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # restart: unless-stopped

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    env_file:
      - .env
    depends_on:
      - redis_server
      - fastapi_app
    command: >
      poetry run celery -A app.worker worker --concurrency=1 --loglevel=info

  # Worker xử lý task hằng giờ (ví dụ: từ Celery Beat hoặc APScheduler)

  # worker_priority_sources:
  #   build:
  #     context: .
  #   container_name: worker_priority_sources
  #   volumes:
  #     - ./src:/app/src
  #     - ./pyproject.toml:/app/pyproject.toml
  #     - ./poetry.lock:/app/poetry.lock
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis_server
  #     - fastapi_app
  #   command: >
  #     poetry run celery -A app.worker worker --concurrency=3 --loglevel=info -Q priority_sources -n priority_sources@%h

  worker_tiktok_sources:
    build:
      context: .
    container_name: worker_tiktok_sources
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    env_file:
      - .env
    depends_on:
      - redis_server
      - fastapi_app
    command: >
      poetry run celery -A app.worker worker --concurrency=3 --loglevel=info -Q tiktok_sources -n tiktok_sources@%h
  worker_tiktok_posts:
    build:
      context: .
    container_name: worker_tiktok_posts
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    env_file:
      - .env
    depends_on:
      - redis_server
      - fastapi_app
    command: >
      poetry run celery -A app.worker worker --concurrency=3 --loglevel=info -Q tiktok_posts -n tiktok_posts@%h
  worker_tiktok_comments:
    build:
      context: .
    container_name: worker_tiktok_comments
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    env_file:
      - .env
    depends_on:
      - redis_server
      - fastapi_app
    command: >
      poetry run celery -A app.worker worker --concurrency=3 --loglevel=info -Q tiktok_comments -n tiktok_comments@%h




  worker_thread:
    build:
      context: .
    container_name: worker_thread
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    env_file:
      - .env
    depends_on:
      - redis_server
      - fastapi_app
    command: >
      poetry run celery -A app.worker worker --concurrency=1 --loglevel=info -Q thread_platform -n thread@%h
  
  # # Lập lịch
  # celery_beat:
  #   build:
  #     context: .
  #   container_name: celery_beat
  #   volumes:
  #     - ./src:/app/src
  #     - ./pyproject.toml:/app/pyproject.toml
  #     - ./poetry.lock:/app/poetry.lock
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis_server
  #     - celery_worker
  #   command: >
  #     poetry run celery -A app.worker beat --loglevel=info

    


  redis_server:
    image: redis:7.2-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # command: ["redis-server", "--appendonly", "yes"]
    # restart: unless-stopped

  flower_dashboard:
    build:
      context: .
      # dockerfile: Dockerfile
    container_name: flower_dashboard
    depends_on:
      - redis_server
      - celery_worker
    env_file:
      - .env
    # environment:
    #   - PYTHONPATH=/app/src
    #   - POETRY_VIRTUALENVS_IN_PROJECT=true
    ports:
      - "5555:5555"
    command: >
      poetry run celery -A app.worker --broker=${REDIS_BROKER_URL} flower --port=5555 
    # restart: unless-stopped

volumes:
  redis_data:
